<?php
/** @var \Perspective\TutorialEntity\Block\EntityRepository $block */
$viewModel = $block->getData('view_model');
?>

<?php if (isset($viewModel)) : ?>
    <?php $product = $viewModel->getProductById('1'); ?>
    <?php if (!is_null($product)) : ?>
        <h2><?= $product->getName(); ?></h2>
        <p><?= $product->getDescription() ?></p>
    <?php endif; ?>

    <hr>

    <?php foreach ($viewModel->getCheapProducts(50) as $cheapProduct): ?>
        <h2><?= $cheapProduct->getName(); ?></h2>
        <h3><?= $cheapProduct->getPrice(); ?></h3>
    <?php endforeach; ?>
<?php endif; ?>

