<?php
/** @var \Perspective\TutorialEntity\ViewModel\ProductInfo $viewModel */
$viewModel = $block->getData('viewModel');
$productsInfo = $viewModel->getProductsInfo('t', 10, 100);
?>

<div>
    <?php foreach ($productsInfo as $product): ?>
        <div>
            Назва: <?php echo $product['name']; ?>
            Ціна: <?php echo $product['price']; ?>
        </div>
    <?php endforeach; ?>
   </div>
